- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Update repositories cache and upgrade packages
    ansible.builtin.apt:
      update_cache: true
      upgrade: true

  - name: Install packages
    ansible.builtin.apt:
      package:
        - wget
        - curl
      state: present

  - name: Install zsh
    ansible.builtin.apt:
      name: zsh
      state: present
