- name: Play for setting up local environment
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories cache and upgrade packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Install essential packages
      ansible.builtin.apt:
        package:
          - wget
          - curl
          - vim
          - git
        state: present

  tasks:
    # - name: Install zsh and oh-my-zsh
    #   ansible.builtin.include_role:
    #     name: zsh

    # - name: Install Pyenv, Python and Poetry
    #   ansible.builtin.include_role:
    #     name: python

    # - name: Install nvm and node
    #   ansible.builtin.include_role:
    #     name: node

    # - name: Install docker
    #   ansible.builtin.include_role:
    #     name: docker
    #


    - name: Import repo signing key
      ansible.builtin.apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Create file repo configuration
      ansible.builtin.apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
        state: present
        filename: "pgdg.list"


    - name: Install postgresql
      ansible.builtin.apt:
        name: postgresql
        state: present
