- name: Play for setting up local environment
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories cache and upgrade packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Install essential packages
      ansible.builtin.apt:
        package:
          - wget
          - curl
          - vim
          - git
        state: present

  tasks:
    - name: Install zsh and oh-my-zsh
      ansible.builtin.include_role:
        name: zsh

    - name: Install Pyenv, Python and Poetry
      ansible.builtin.include_role:
        name: python

    - name: Install nvm and node
      ansible.builtin.include_role:
        name: node

    - name: Install docker
      ansible.builtin.include_role:
        name: docker
