- name: Play for setting up local environment
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories cache and upgrade packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

  tasks:
    - name: Install important packages
      ansible.builtin.apt:
        package:
          - wget
          - curl
          - vim
          - git
        state: present

    - name: Install zsh and oh-my-zsh
      ansible.builtin.include_role:
        name: zsh

    - name: Install Pyenv, Python and Poetry
      ansible.builtin.include_role:
        name: python

    - name: Install nvm
      ansible.builtin.shell: set -o pipefail && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
      args:
        executable: /bin/bash
        creates: "~hh/.nvm/nvm.sh"

    - name: Install node
      ansible.builtin.shell: "~hh/.nvm/nvm.sh && nvm install node"
      args:
        executable: /bin/bash
        creates: "~hh/.nvm/versions/node/v20.5.1/bin/node"
