- name: Rabbitmq prerequisites
  ansible.builtin.apt:
    name:
      - gnupg
      - apt-transport-https

- name: Add Rabbitmq main signing key
  ansible.builtin.apt_key:
    url: "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA"
    keyring: "/usr/share/keyrings/com.rabbitmq.team.gpg"

- name: Add Erlang signing key
  ansible.builtin.apt_key:
    url: https://ppa.novemberain.com/gpg.E495BB49CC4BBE5B.key
    keyring: /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg

- name: Add Rabbitmq community signing key
  ansible.builtin.apt_key:
    url: https://ppa.novemberain.com/gpg.9F4587F226208342.key
    keyring: /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg

- name: Add Rabbitmq repository to source
  ansible.builtin.template:
    src: files/rabbitmq/rabbitmq.list.j2
    dest: /etc/apt/sources.list.d/rabbitmq.list
    mode: "0644"

- name: Install Erlang
  ansible.builtin.apt:
    name:
      - erlang-base
      - erlang-asn1
      - erlang-crypto
      - erlang-eldap
      - erlang-ftp
      - erlang-inets
      - erlang-mnesia
      - erlang-os-mon
      - erlang-parsetools
      - erlang-public-key
      - erlang-runtime-tools
      - erlang-snmp
      - erlang-ssl
      - erlang-syntax-tools
      - erlang-tftp
      - erlang-tools
      - erlang-xmerl

- name: Install Rabbmitmq
  ansible.builtin.apt:
    name: rabbitmq-server
    state: present
