- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Install `oh-my-zsh`
  become_user: "{{ user }}"
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "~{{ user }}/.oh-my-zsh/oh-my-zsh.sh"

- name: Copy `.zshrc` file
  become_user: hh
  ansible.builtin.copy:
    src: "{{ zsh_file }}"
    dest: "~{{ user }}/.zshrc"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rw,g=r,o=r

- name: change shell to zsh
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
