- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Install `oh-my-zsh`
  become_user: "{{ user }}"
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "~{{ user }}/.oh-my-zsh/oh-my-zsh.sh"

- name: Clone dotfiles folder
  become_user: hh
  ansible.builtin.git:
    repo: git@github.com:hanhwanglim/dotfiles.git
    dest: /tmp/dotfiles
    version: main
    depth: 1

- name: Copy dotfiles folder
  become_user: hh
  ansible.builtin.copy:
    src: "/tmp/dotfiles"
    dest: "~{{ user }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"

- name: Change shell to zsh
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /usr/bin/zsh

- name: Remove default zshrc file
  ansible.builtin.file:
    name: "~{{ user }}/.zshrc"
    state: absent

- name: Add symlinks
  become_user: "{{ user }}"
  ansible.builtin.script:
    cmd: "configure.py work"
  args:
    executable: python3
    creates: "~{{ user }}/.zshrc"
    chdir: "~hh/dotfiles"

- name: Install plugins
  block:
    - name: Install direnv
      become_user: hh
      ansible.builtin.shell:
        cmd: set -o pipefail && curl -sfL https://direnv.net/install.sh | bash
        environment:
          - bin_path: "/usr/bin"
      args:
        creates: "/usr/bin/direnv"
    - name: Install Atuin
      become_user: hh
      ansible.builtin.shell:
        cmd: bash <(curl https://raw.githubusercontent.com/atuinsh/atuin/main/install.sh)
      args:
        creates: "/usr/bin/atuin"
