- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Install `oh-my-zsh`
  become_user: "{{ user }}"
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "~{{ user }}/.oh-my-zsh/oh-my-zsh.sh"

- name: Copy dotfiles folder
  become_user: hh
  ansible.builtin.copy:
    src: "files/dotfiles"
    dest: "~{{ user }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"

- name: Change shell to zsh
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /usr/bin/zsh

- name: Remove default zshrc file
  ansible.builtin.file:
    name: "{{ user }}/.zshrc"

- name: Add symlinks
  become_user: "{{ user }}"
  ansible.builtin.command:
    cmd: "~{{ user }}/dotfiles/configure.sh"
  args:
    creates: "~{{ user }}/.zshrc"
