- name: Install Docker (Ubuntu)
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Install Docker (Fedora)
  ansible.builtin.include_tasks: fedora.yml
  when: ansible_facts["distribution"] == "Fedora"
