- name: Play for setting up local environment
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories cache and upgrade packages (Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      when: ansible_facts["distribution"] == "Ubuntu"

    - name: Update repositories cache and upgrade packages (Fedora)
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_facts["distribution"] == "Fedora"

    - name: Install essential packages
      ansible.builtin.apt:
        package:
          - wget
          - curl
          - vim
          - git
          - lsb-release
          - unzip
          - make
        state: present
      when: ansible_facts["distribution"] == "Ubuntu"

    - name: Install essential packages
      ansible.builtin.dnf:
        package:
          - wget
          - curl
          - vim
          - git
          - lsb-release
          - unzip
          - make
        state: present
      when: ansible_facts["distribution"] == "Fedora"

  tasks:
    - name: Install zsh and oh-my-zsh
      ansible.builtin.include_role:
        name: zsh

    - name: Install Pyenv, Python and Poetry
      ansible.builtin.include_role:
        name: python

    - name: Install nvm and node
      ansible.builtin.include_role:
        name: node

    - name: Install docker
      ansible.builtin.include_role:
        name: docker

    - name: Install postgresql
      ansible.builtin.include_role:
        name: postgresql

    - name: Install Redis
      ansible.builtin.include_role:
        name: redis

    - name: Install Rabbitmq
      ansible.builtin.include_role:
        name: rabbitmq

    - name: Install aws cli
      ansible.builtin.include_role:
        name: aws
